### PR TITLE
My rudimentary solution

### PR DESCRIPTION
**Pull request by erdostom**
Probably not the prettiest, but it works. Also, apologies for not using tests. Can you recommend resources for using tests for non-rails development?

Thank you for doing this contest. This is my first programming contest submission (of any kind).

### CODE REVIEW

**Comment by JESii** [comment]
Hi, @erdostom... For tests on non-Rails applications, there are two books you can try out, both from pragprog.com: "The Rspec Book" (http://pragprog.com/book/achbd/the-rspec-book) and "Command-Line Apps in Ruby" (http://pragprog.com/book/dccar/build-awesome-command-line-applications-in-ruby). I couldn't find any good tutorials online...

**Comment by erdostom** [comment]
Thanks @JESii i . I will check out the books you mentioned. I will also clean up the whitespace, improve readability and make another commit.

**Comment by GCorbel** [comment]
I agree with @JESii, I also think than you should separate your code in classes. You should also make smallest methods. Ideally, a class should not be longer than 100 lines and a method should not be longer than 5 lines. I recommand you to read about [Single Responsability Principle](http://en.wikipedia.org/wiki/Single_responsibility_principle).

**Comment by JESii** [comment]
Also, I don't see that you're printing out the errors that result in the sudoku being invalid?

**Comment by mrhead** [comment]
@erdostom I've wrote some posts about testing of ruby scripts:

http://rubybeginner.com/how-to-test-ruby-scripts-with-rspec.html
http://rubybeginner.com/ruby-fizzbuzz-kata-with-tdd.html

I hope that it will help you. If not feel free to ask questions. Here or on my blog.

**Pull request closed without merging**
